# Route admin pour la GED
documents_new:
    path:     /documents/nouveau
    defaults: { _controller: "GedBundle:Documents:new" }

documents_create:
    path:     /documents/create
    defaults: { _controller: "GedBundle:Documents:create" }
    methods:  POST

documents_edit:
    path:     /documents/{id}/edit/
    defaults: { _controller: "GedBundle:Documents:edit" }

documents_update:
    path:     /documents/{id}/update
    defaults: { _controller: "GedBundle:Documents:update" }
    methods:  [POST, PUT]

documents_delete:
    path:     /documents/{id}/delete
    defaults: { _controller: "GedBundle:Documents:delete" }
    requirements:
        id:  \d+

# Route admin pour la gestion utilisateur
fos_user_registration_register:
    path:     /register
    defaults: { _controller: "UserBundle:Registration:register" }
    requirements:
        id:  \d+

user_delete:
    path:     /user/{id}/delete
    defaults: { _controller: "UserBundle:User:delete" }
    requirements:
        id:  \d+

# Route pour la gestion des organismes

admin_organisme:
    path:     /organisme/
    defaults: { _controller: "AppBundle:Organisme:index" }

admin_organisme_new:
    path:     /organisme/new
    defaults: { _controller: "AppBundle:Organisme:new" }

admin_organisme_create:
    path:     /organisme/create
    defaults: { _controller: "AppBundle:Organisme:create" }
    methods:  POST

admin_organisme_edit:
    path:     /organisme/{id}/edit
    defaults: { _controller: "AppBundle:Organisme:edit" }

admin_organisme_update:
    path:     /organisme/{id}/update
    defaults: { _controller: "AppBundle:Organisme:update" }
    methods:  [POST, PUT]

admin_organisme_delete:
    path:     /organisme/{id}/delete
    defaults: { _controller: "AppBundle:Organisme:delete" }
    methods:  [POST, DELETE, GET]

organisme_get_picture:
    path:      /organisme/{picture}
    defaults: { _controller: "AppBundle:Organisme:PictureOrganisme" }
    methods: [GET]

# Route admin pour la gestion des évènements AgendaBundle

events_new:
    path:     event/{start}/new
    defaults: { _controller: "AgendaBundle:Events:new" }

events_create:
    path:     event/create
    defaults: { _controller: "AgendaBundle:Events:create" }
    methods:  POST

events_edit:
    path:     event/{id}/edit
    defaults: { _controller: "AgendaBundle:Events:edit" }

events_update:
    path:     event/{id}/update
    defaults: { _controller: "AgendaBundle:Events:update" }
    methods:  [POST, PUT]

events_delete:
    path:     event/{id}/delete
    defaults: { _controller: "AgendaBundle:Events:delete" }
    requirements:
        id:  \d+

