message:
    path:     /
    defaults: { _controller: "MsgBundle:Message:index" }

message_show:
    path:     /{id}/show
    defaults: { _controller: "MsgBundle:Message:show" }

message_new:
    path:     /new/
    defaults: { _controller: "MsgBundle:Message:new" }

message_new_email:
    path:     /new/{email}/
    defaults: { _controller: "MsgBundle:Message:new" }

message_suivi:
    path:     /discussion
    defaults: { _controller: "MsgBundle:Message:subject" }

message_create:
    path:     /create
    defaults: { _controller: "MsgBundle:Message:create" }
    methods:  POST

#message_edit:
#    path:     /{id}/edit
#    defaults: { _controller: "MsgBundle:Message:edit" }

message_update:
    path:     /{id}/update
    defaults: { _controller: "MsgBundle:Message:update" }
    methods:  [POST, PUT]

message_delete:
    path:     /{id}/delete
    defaults: { _controller: "MsgBundle:Message:delete" }
    methods:  [POST, DELETE]
